---
- hosts: test-server
  become: true
  tasks:
  - name: update apt
    command: sudo apt-get update

  - name: install docker
    command: sudo apt install -y docker.io

  - name: start docker service
    command: sudo systemctl start docker

  - name: Check if docker container exists
    command: docker ps -aqf "name=insure-me"
    register: docker_container_id
    ignore_errors: yes

  - name: Stop and remove container if it exists
    command: docker rm -f "{{ docker_container_id.stdout }}" if docker_container_id.rc == 0 else echo "Container does not exist or not running."
    ignore_errors: yes

  - name: deploy insureme application
    command: sudo docker run -itd -p 8081:8081 --name insure-me harshgoti/insure-me:1.0

  - name: Install maven
    apt:
      name: maven
      state: present
      update_cache: true