---
- hosts: test-server
  become: true
  tasks:
  - name: update apt
    command: sudo apt-get update

  - name: install docker
    command: sudo apt install -y docker.io

  - name: start docker service
    command: sudo systemctl start docker

  - name: stop docker container
    command: sudo docker stop insure-me

  - name: deploy insureme application
    command: sudo docker run -itd -p 8081:8081 --name insure-me harshgoti/insure-me:1.0
// write ansible playbook using above script, if docker container is exist and running then stop and remove