---
- hosts: test-server
  become: true
  tasks:
  - name: update apt
    command: sudo apt-get update

  - name: install docker
    command: sudo apt install -y docker.io

  - name: start docker service
    command: sudo systemctl start docker

  - name: remove container if exist
    command: docker rm -f "{{ docker_container_info.container_id }}" if docker_container_info.exists else echo "Container does not exist."
    ignore_errors: yes

  - name: deploy insureme application
    command: sudo docker run -itd -p 8081:8081 --name insure-me harshgoti/insure-me:1.0
