---
- hosts: test-server
  become: true
  tasks:
  - name: update apt
    command: sudo apt-get update

  - name: install docker
    command: sudo apt install -y docker.io

  - name: start docker service
    command: sudo systemctl start docker

  - name: Check if the container is running
    command: sudo docker ps --filter name=insure-me --format "{{ .Names }}"
    register: container_running
    ignore_errors: yes

  - name: Stop and remove the container if it is running
    command: sudo docker rm -f insure-me
    when: container_running.stdout_lines and container_running.stdout_lines[0] == 'insure-me'

  - name: deploy insureme application
    command: sudo docker run -itd -p 8081:8081 --name insure-me harshgoti/insure-me:1.0
