---
- hosts: test-server
  become: true
  tasks:
  - name: update apt
    command: sudo apt-get update

  - name: install docker
    command: sudo apt install -y docker.io

  - name: start docker service
    command: sudo systemctl start docker

  - name: Check if the container exists and is running
    docker_container_info:
      name: insure-me
    register: container_status
    ignore_errors: yes

  - name: Stop and remove the container if it exists and is running
    command: sudo docker rm -f insure-me
    when: container_status.exists and container_status.running

  - name: deploy insureme application
    command: sudo docker run -itd -p 8081:8081 --name insure-me harshgoti/insure-me:1.0
