---
- hosts: test-server
  become: true
  tasks:
  - name: update apt
    command: sudo apt-get update

  - name: install docker
    command: sudo apt install -y docker.io

  - name: start docker service
    command: sudo systemctl start docker

  - name: Install pip
    apt:
      name: python3-pip
      state: present
      update_cache: true

  - name: Install Docker
    pip:
      name: docker

  - name: Start Docker service
    service:
      name: docker
      state: started

  - name: remove container
    docker_container:
      name: insure-me
      state: absent

  - name: deploy insureme application
    docker_container:
      name: insure-me
      image: harshgoti/insure-me:1.0
      state: started
      ports:
        - "8081:8081"
